//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IModelService")]
public interface IModelService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/GetList", ReplyAction="http://tempuri.org/IModelService/GetListResponse")]
    int[] GetList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/GetList", ReplyAction="http://tempuri.org/IModelService/GetListResponse")]
    System.Threading.Tasks.Task<int[]> GetListAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IModelServiceChannel : IModelService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ModelServiceClient : System.ServiceModel.ClientBase<IModelService>, IModelService
{
    
    public ModelServiceClient()
    {
    }
    
    public ModelServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ModelServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ModelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ModelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int[] GetList()
    {
        return base.Channel.GetList();
    }
    
    public System.Threading.Tasks.Task<int[]> GetListAsync()
    {
        return base.Channel.GetListAsync();
    }
}
